baseURL = "https://a816-dohbesp.nyc.gov/IndicatorPublic/"
canonifyURLs = false
relativeURLs = false
languageCode = "en-us"
title = "Environment & Health Data Portal"
enableRobotsTXT = true
metaDataFormat = "yaml"
theme = "dohmh"
publishDir = "docs"
paginate = 9
ignoreFiles = ['Simplified.Chinese', 'Spanish']

[params]
  data_repo = "https://raw.githubusercontent.com/nychealth/EHDP-data/"

[caches]
    [caches.getresource]
      dir = ':cacheDir/:project'
      maxAge = -1

[imaging]
  anchor = 'Smart'
  bgColor = '#ffffff'
  hint = 'photo'
  quality = 95
  resampleFilter = 'MitchellNetravali'

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[languages.en]
  languageName = "English"
  weight = 1
  [languages.en.params]
    languageDesc = "English"

[languages.es]
  languageName = "Español"
  weight = 2
  [languages.es.params]
    languageDesc = "Spanish-US"

[languages.zh]
  languageName = "中文"
  weight = 3
  [languages.zh.params]
    languageDesc = "Chinese-Simplified"


[taxonomies]
  tag = "tags"
  category = "categories"
  keyword = "keywords"


[menu]

  [[menu.main]]
    identifier = "02"
    name = "Publications"
    pre = "<span class='firm-blue'><i class='fas fa-book-open' aria-hidden='true'></i></span>"
    url = "/publications/"
    weight = -90
  
  [[menu.main]]
    identifier = "03"
    name = "Dashboards"
    pre = "<span class='firm-blue'><i class='fas fa-chart-line' aria-hidden='true'></i></span>"
    url = "/dashboards/"
    weight = -100
  
  [[menu.main]]
    identifier = "04"
    name = "Topics"
    pre = "<span class='firm-blue'><i class='fas fa-sitemap' aria-hidden='true'></i></span>"
    url = "/topics/"
    weight = -105

  [[menu.main]]
    identifier = "05"
    name = "Tools"
    pre = "<span class='firm-blue'><i class='fas fa-tools mr-1' aria-hidden='true'></i></span>"
    url = "/tools/"
    weight = -110

  [[menu.main]]
    identifier = "06"
    name = "Search"
    # pre = "<span class='sr-only'>Search</span><span class='fas fa-search fa-lg'></span>"
    # url = ""
    weight = -50


[module]

  [[module.mounts]]
    source = "node_modules"
    target = "assets/node_modules"

 [[module.mounts]]
    source = "content"
    target = "content"

  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "layouts"
    target = "layouts"

  [[module.mounts]]
    source = "data"
    target = "data"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "i18n"
    target = "i18n"

  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"